In [4]:
import pandas as pd  
import numpy as np 
import plotly.express as px

In [5]:
df= pd.read_csv('train.csv')
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,Engine,Power,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,26.6 km/kg,998 CC,58.16 bhp,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67 kmpl,1582 CC,126.2 bhp,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.2 kmpl,1199 CC,88.7 bhp,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77 kmpl,1248 CC,88.76 bhp,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.2 kmpl,1968 CC,140.8 bhp,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.4 kmpl,1248 CC,74 bhp,5.0,7.88 Lakh,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.4 kmpl,1120 CC,71 bhp,5.0,NaN,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.0 kmpl,2498 CC,112 bhp,8.0,NaN,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.9 kmpl,998 CC,67.1 bhp,5.0,NaN,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44 kmpl,936 CC,57.6 bhp,5.0,NaN,2.50

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6019 entries, 0 to 6018
Data columns (total 13 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               6019 non-null   object
 1   Location           6019 non-null   object
 2   Year               6019 non-null   int64
 3   Kilometers_Driven  6019 non-null   int64
 4   Fuel_Type          6019 non-null   object
 5   Transmission       6019 non-null   object
 6   Owner_Type         6019 non-null   object
 7   Mileage            6017 non-null   object
 8   Engine             5983 non-null   object
 9   Power              5983 non-null   object
 10  Seats              5977 non-null   float64
 11  New_Price          824 non-null    object
 12  Price              6019 non-null   float64
dtypes: float64(2), int64(2), object(9)
memory usage: 611.4+ KB

In [7]:
df.describe().round(2)

          Year  Kilometers_Driven    Seats    Price
count  6019.00            6019.00  5977.00  6019.00
mean   2013.36           58738.38     5.28     9.48
std       3.27           91268.84     0.81    11.19
min    1998.00             171.00     0.00     0.44
25%    2011.00           34000.00     5.00     3.50
50%    2014.00           53000.00     5.00     5.64
75%    2016.00           73000.00     5.00     9.95
max    2019.00         6500000.00    10.00   160.00

In [8]:
df = df[(df['Seats'] >= 1) & (df['Seats'] < 10 )].copy()

In [9]:
object_col = df.describe(include='object').columns
object_col

Index(['Name', 'Location', 'Fuel_Type', 'Transmission', 'Owner_Type',
       'Mileage', 'Engine', 'Power', 'New_Price'],
      dtype='object')

In [10]:
for col in object_col:
    print(col)
    print(df[col].nunique)
    print(df[col].unique)
    print('\n' , 50* '=' , '\n')

Name
<bound method IndexOpsMixin.nunique of 0                 Maruti Wagon R LXI CNG
1       Hyundai Creta 1.6 CRDi SX Option
2                           Honda Jazz V
3                      Maruti Ertiga VDI
4        Audi A4 New 2.0 TDI Multitronic
                      ...
6014                    Maruti Swift VDI
6015            Hyundai Xcent 1.1 CRDi S
6016               Mahindra Xylo D4 BSIV
6017                  Maruti Wagon R VXI
6018               Chevrolet Beat Diesel
Name: Name, Length: 5971, dtype: object>
<bound method Series.unique of 0                 Maruti Wagon R LXI CNG
1       Hyundai Creta 1.6 CRDi SX Option
2                           Honda Jazz V
3                      Maruti Ertiga VDI
4        Audi A4 New 2.0 TDI Multitronic
                      ...
6014                    Maruti Swift VDI
6015            Hyundai Xcent 1.1 CRDi S
6016               Mahindra Xylo D4 BSIV
6017                  Maruti Wagon R VXI
6018               Chevrolet Beat Diesel
Name: Name, Length: 5971, dtype: object>

 ==================================================

Location
<bound method IndexOpsMixin.nunique of 0           Mumbai
1             Pune
2          Chennai
3          Chennai
4       Coimbatore
           ...
6014         Delhi
6015        Jaipur
6016        Jaipur
6017       Kolkata
6018     Hyderabad
Name: Location, Length: 5971, dtype: object>
<bound method Series.unique of 0           Mumbai
1             Pune
2          Chennai
3          Chennai
4       Coimbatore
           ...
6014         Delhi
6015        Jaipur
6016        Jaipur
6017       Kolkata
6018     Hyderabad
Name: Location, Length: 5971, dtype: object>

 ==================================================

Fuel_Type
<bound method IndexOpsMixin.nunique of 0          CNG
1       Diesel
2       Petrol
3       Diesel
4       Diesel
         ...
6014    Diesel
6015    Diesel
6016    Diesel
6017    Petrol
6018    Diesel
Name: Fuel_Type, Length: 5971, dtype: object>
<bound method Series.unique of 0          CNG
1       Diesel
2       Petrol
3       Diesel
4       Diesel
         ...
6014    Diesel
6015    Diesel
6016    Diesel
6017    Petrol
6018    Diesel
Name: Fuel_Type, Length: 5971, dtype: object>

 ==================================================

Transmission
<bound method IndexOpsMixin.nunique of 0          Manual
1          Manual
2          Manual
3          Manual
4       Automatic
          ...
6014       Manual
6015       Manual
6016       Manual
6017       Manual
6018       Manual
Name: Transmission, Length: 5971, dtype: object>
<bound method Series.unique of 0          Manual
1          Manual
2          Manual
3          Manual
4       Automatic
          ...
6014       Manual
6015       Manual
6016       Manual
6017       Manual
6018       Manual
Name: Transmission, Length: 5971, dtype: object>

 ==================================================

Owner_Type
<bound method IndexOpsMixin.nunique of 0        First
1        First
2        First
3        First
4       Second
         ...
6014     First
6015     First
6016    Second
6017     First
6018     First
Name: Owner_Type, Length: 5971, dtype: object>
<bound method Series.unique of 0        First
1        First
2        First
3        First
4       Second
         ...
6014     First
6015     First
6016    Second
6017     First
6018     First
Name: Owner_Type, Length: 5971, dtype: object>

 ==================================================

Mileage
<bound method IndexOpsMixin.nunique of 0       26.6 km/kg
1       19.67 kmpl
2        18.2 kmpl
3       20.77 kmpl
4        15.2 kmpl
           ...
6014     28.4 kmpl
6015     24.4 kmpl
6016     14.0 kmpl
6017     18.9 kmpl
6018    25.44 kmpl
Name: Mileage, Length: 5971, dtype: object>
<bound method Series.unique of 0       26.6 km/kg
1       19.67 kmpl
2        18.2 kmpl
3       20.77 kmpl
4        15.2 kmpl
           ...
6014     28.4 kmpl
6015     24.4 kmpl
6016     14.0 kmpl
6017     18.9 kmpl
6018    25.44 kmpl
Name: Mileage, Length: 5971, dtype: object>

 ==================================================

Engine
<bound method IndexOpsMixin.nunique of 0        998 CC
1       1582 CC
2       1199 CC
3       1248 CC
4       1968 CC
         ...
6014    1248 CC
6015    1120 CC
6016    2498 CC
6017     998 CC
6018     936 CC
Name: Engine, Length: 5971, dtype: object>
<bound method Series.unique of 0        998 CC
1       1582 CC
2       1199 CC
3       1248 CC
4       1968 CC
         ...
6014    1248 CC
6015    1120 CC
6016    2498 CC
6017     998 CC
6018     936 CC
Name: Engine, Length: 5971, dtype: object>

 ==================================================

Power
<bound method IndexOpsMixin.nunique of 0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...
6014       74 bhp
6015       71 bhp
6016      112 bhp
6017     67.1 bhp
6018     57.6 bhp
Name: Power, Length: 5971, dtype: object>

<bound method Series.unique of 0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...
6014       74 bhp
6015       71 bhp
6016      112 bhp
6017     67.1 bhp
6018     57.6 bhp
Name: Power, Length: 5971, dtype: object>

 ==================================================

New_Price
<bound method IndexOpsMixin.nunique of 0             NaN
1             NaN
2       8.61 Lakh
3             NaN
4             NaN
          ...
6014    7.88 Lakh
6015          NaN
6016          NaN
6017          NaN
6018          NaN
Name: New_Price, Length: 5971, dtype: object>
<bound method Series.unique of 0             NaN
1             NaN
2       8.61 Lakh
3             NaN
4             NaN
          ...
6014    7.88 Lakh
6015          NaN
6016          NaN
6017          NaN
6018          NaN
Name: New_Price, Length: 5971, dtype: object>

 ==================================================

In [11]:
df = df.rename(columns={'Engine': 'engine_capacity(cc)'})

In [12]:
df.rename(columns={'Power' :'Power_bhp'} ,  inplace=True)

In [13]:
df['engine_capacity(cc)'] = df['engine_capacity(cc)'].str.replace('CC',"").astype('int')

In [14]:
df.Power_bhp

0       58.16 bhp
1       126.2 bhp
2        88.7 bhp
3       88.76 bhp
4       140.8 bhp
          ...
6014       74 bhp
6015       71 bhp
6016      112 bhp
6017     67.1 bhp
6018     57.6 bhp
Name: Power_bhp, Length: 5971, dtype: object

In [15]:
df['Power_bhp'] = df['Power_bhp'].str.replace('bhp','')

In [16]:
df['Power_bhp'] = df['Power_bhp'].replace('null ',np.nan).astype('float64')

In [17]:
df['Mileage'].unique()

array(['26.6 km/kg', '19.67 kmpl', '18.2 kmpl', '20.77 kmpl', '15.2 kmpl',
       '21.1 km/kg', '23.08 kmpl', '11.36 kmpl', '20.54 kmpl',
       '22.3 kmpl', '21.56 kmpl', '16.8 kmpl', '25.2 kmpl', '12.7 kmpl',
       '0.0 kmpl', '13.5 kmpl', '25.8 kmpl', '28.4 kmpl', '20.45 kmpl',
       '14.84 kmpl', '22.69 kmpl', '23.65 kmpl', '13.53 kmpl',
       '18.5 kmpl', '14.4 kmpl', '20.92 kmpl', '17.5 kmpl', '12.8 kmpl',
       '19.01 kmpl', '14.53 kmpl', '11.18 kmpl', '12.4 kmpl',
       '16.09 kmpl', '14.0 kmpl', '24.3 kmpl', '18.15 kmpl', '11.74 kmpl',
       '22.07 kmpl', '19.7 kmpl', '25.4 kmpl', '25.32 kmpl', '14.62 kmpl',
       '14.28 kmpl', '14.9 kmpl', '11.25 kmpl', '24.4 kmpl', '16.55 kmpl',
       '17.11 kmpl', '22.9 kmpl', '17.8 kmpl', '18.9 kmpl', '15.04 kmpl',
       '25.17 kmpl', '20.36 kmpl', '13.29 kmpl', '13.68 kmpl',
       '20.0 kmpl', '15.8 kmpl', '25.0 kmpl', '16.4 kmpl', '24.52 kmpl',
       '22.1 kmpl', '8.5 kmpl', '15.1 kmpl', '16.95 kmpl', '19.64 kmpl',
       '16.5 kmpl', '18.53 kmpl', '17.57 kmpl', '18.0 kmpl', '23.2 kmpl',
       '16.73 kmpl', '17.0 kmpl', '13.0 kmpl', '17.68 kmpl', '22.7 kmpl',
       '16.2 kmpl', '15.26 kmpl', '23.0 kmpl', '19.83 kmpl', '14.94 kmpl',
       '17.71 kmpl', '14.74 kmpl', '16.0 kmpl', '22.32 kmpl',
       '12.99 kmpl', '23.3 kmpl', '19.15 kmpl', '10.8 kmpl', '15.0 kmpl',
       '22.0 kmpl', '21.9 kmpl', '12.05 kmpl', '11.7 kmpl', '21.21 kmpl',
       '20.73 kmpl', '21.1 kmpl', '24.07 kmpl', '19.0 kmpl', '20.58 kmpl',
       '19.27 kmpl', '11.5 kmpl', '18.6 kmpl', '21.14 kmpl', '11.05 kmpl',
       '21.76 kmpl', '7.81 kmpl', '21.66 kmpl', '17.2 kmpl', '20.63 kmpl',
       '19.4 kmpl', '14.8 kmpl', '26.0 kmpl', '20.4 kmpl', '21.5 kmpl',
       '15.3 kmpl', '17.9 kmpl', '16.6 kmpl', '22.54 kmpl', '25.44 kmpl',
       '13.7 kmpl', '22.48 kmpl', '12.9 kmpl', '19.98 kmpl', '21.4 kmpl',
       '19.81 kmpl', '15.4 kmpl', '25.47 kmpl', '19.87 kmpl',
       '17.45 kmpl', '14.7 kmpl', '15.64 kmpl', '15.73 kmpl',
       '23.59 kmpl', '27.4 kmpl', '20.46 kmpl', '15.29 kmpl',
       '20.51 kmpl', '11.8 kmpl', '14.3 kmpl', '14.67 kmpl', '17.19 kmpl',
       '21.03 kmpl', '22.5 kmpl', '16.82 kmpl', '11.72 kmpl', '17.4 kmpl',
       '17.05 kmpl', '24.0 kmpl', '28.09 kmpl', '20.5 kmpl', '13.1 kmpl',
       '19.91 kmpl', '18.7 kmpl', '16.38 kmpl', '11.57 kmpl', '17.3 kmpl',
       '22.95 kmpl', '18.88 kmpl', '23.4 kmpl', '22.74 kmpl',
       '12.07 kmpl', '17.1 kmpl', '18.48 kmpl', '16.47 kmpl', '23.1 kmpl',
       '14.07 kmpl', '16.02 kmpl', '19.3 kmpl', '17.7 kmpl', '9.52 kmpl',
       '14.75 kmpl', '26.3 km/kg', '11.3 kmpl', '21.12 kmpl',
       '21.02 kmpl', '14.45 kmpl', '19.33 kmpl', '13.8 kmpl', '24.7 kmpl',
       '11.0 kmpl', '11.07 kmpl', '16.1 kmpl', '21.43 kmpl', '14.21 kmpl',
       '18.86 kmpl', '16.07 kmpl', '13.49 kmpl', '20.38 kmpl',
       '12.0 kmpl', '17.01 kmpl', '13.2 kmpl', '20.37 kmpl', '15.1 km/kg',
       '15.96 kmpl', '14.16 kmpl', '13.17 kmpl', '27.62 kmpl',
       '25.1 kmpl', '15.17 kmpl', '11.33 kmpl', '17.92 kmpl',
       '12.55 kmpl', '12.6 kmpl', '17.72 kmpl', '18.16 kmpl',
       '15.68 kmpl', '15.5 kmpl', '12.1 kmpl', '14.83 kmpl', '17.6 kmpl',
       '14.6 kmpl', '14.66 kmpl', '10.93 kmpl', '20.68 kmpl', '9.9 kmpl',
       '21.13 kmpl', '20.14 kmpl', '19.2 kmpl', '27.3 kmpl', '16.36 kmpl',
       '26.59 kmpl', '12.5 kmpl', '13.6 kmpl', '15.06 kmpl', '10.13 kmpl',
       '17.21 kmpl', '15.97 kmpl', '10.5 kmpl', '14.69 kmpl', '23.9 kmpl',
       '19.1 kmpl', '21.27 kmpl', '15.9 kmpl', '20.7 kmpl', '14.1 kmpl',
       '20.89 kmpl', '18.12 kmpl', '12.3 kmpl', '19.71 kmpl', '9.43 kmpl',
       '13.4 kmpl', '13.14 kmpl', '18.1 kmpl', '22.77 kmpl', '14.49 kmpl',
       '12.39 kmpl', '10.91 kmpl', '20.85 kmpl', '15.63 kmpl',
       '27.39 kmpl', '18.3 kmpl', '16.78 kmpl', '25.5 kmpl', '10.0 kmpl',
       '13.73 kmpl', '24.2 kmpl', '14.02 kmpl', '26.83 km/kg',
       '16.77 kmpl', '24.5 kmpl', '20.34 kmpl', '21.7 kmpl', '9.7 kmpl',
       '14.33 kmpl', '21.64 kmpl', '13.2 km/kg', '19.16 kmpl',
       '16.93 kmpl', '9.0 kmpl', '26.2 km/kg', '16.3 kmpl', '12.62 kmpl',
       '17.3 km/kg', '20.64 kmpl', '14.24 kmpl', '18.06 kmpl',
       '10.2 kmpl', '10.1 kmpl', '18.25 kmpl', '13.93 kmpl', '25.83 kmpl',
       '8.6 kmpl', '13.24 kmpl', '17.09 kmpl', '23.84 kmpl', '8.45 kmpl',
       '19.6 kmpl', '19.5 kmpl', '20.3 kmpl', '16.05 kmpl', '11.2 kmpl',
       '27.03 kmpl', '18.78 kmpl', '12.35 kmpl', '14.59 kmpl',
       '17.32 kmpl', '14.95 kmpl', '13.22 kmpl', '23.03 kmpl',
       '33.44 km/kg', '15.6 kmpl', '19.12 kmpl', '10.98 kmpl',
       '33.54 km/kg', '16.46 kmpl', '18.4 kmpl', '11.1 kmpl',
       '13.01 kmpl', '18.8 kmpl', '16.52 kmpl', '18.44 kmpl',
       '19.49 kmpl', '23.5 kmpl', '23.8 kmpl', '12.65 kmpl', '20.65 kmpl',
       '21.72 kmpl', '12.19 kmpl', '26.1 kmpl', '18.33 kmpl',
       '12.81 kmpl', '17.5 km/kg', '17.06 kmpl', '17.67 kmpl',
       '19.34 kmpl', '8.3 kmpl', '16.96 kmpl', '11.79 kmpl', '20.86 kmpl',
       '16.98 kmpl', '11.68 kmpl', '15.74 kmpl', '15.7 kmpl',
       '18.49 kmpl', '10.9 kmpl', '19.59 kmpl', '11.4 kmpl', '13.06 kmpl',
       '21.0 kmpl', '15.15 kmpl', '16.9 kmpl', '18.23 kmpl', '25.0 km/kg',
       '17.16 kmpl', '17.43 kmpl', '19.08 kmpl', '18.56 kmpl',
       '11.9 kmpl', '24.6 km/kg', '21.79 kmpl', '12.95 kmpl', '25.6 kmpl',
       '13.45 km/kg', '26.21 kmpl', '13.58 kmpl', '16.25 kmpl',
       '10.4 kmpl', '17.44 kmpl', '19.2 km/kg', '22.71 kmpl',
       '17.54 kmpl', '22.1 km/kg', '17.0 km/kg', '15.87 kmpl', '9.5 kmpl',
       '11.56 kmpl', '14.39 kmpl', '19.09 kmpl', '17.85 kmpl',
       '31.79 km/kg', '18.18 kmpl', '21.19 kmpl', '21.8 kmpl',
       '15.42 kmpl', '14.47 kmpl', '19.69 kmpl', '12.83 kmpl', '8.0 kmpl',
       '22.8 km/kg', '12.63 kmpl', '14.57 kmpl', '27.28 kmpl',
       '15.41 kmpl', '32.26 km/kg', '18.19 kmpl', '13.33 kmpl',
       '16.7 kmpl', '17.84 kmpl', '20.0 km/kg', '23.19 kmpl',
       '11.49 kmpl', '18.51 kmpl', '13.44 kmpl', '8.7 kmpl', '8.77 kmpl',
       '17.97 kmpl', '23.57 kmpl', '12.37 kmpl', '9.1 kmpl', '12.51 kmpl',
       '19.44 kmpl', '21.38 kmpl', '16.51 kmpl', '24.8 kmpl',
       '14.42 kmpl', '14.53 km/kg', '26.8 kmpl', '24.04 kmpl', '9.8 kmpl',
       '19.68 kmpl', '21.4 km/kg', '21.2 kmpl', '19.72 kmpl', '14.2 kmpl',
       '12.98 kmpl', '23.01 kmpl', '16.12 kmpl', '9.3 kmpl', '15.85 kmpl',
       nan, '17.88 kmpl', '10.6 kmpl', '11.78 kmpl', '7.94 kmpl',
       '25.01 kmpl', '8.1 kmpl', '13.9 kmpl', '11.62 kmpl', '20.62 kmpl',
       '15.11 kmpl', '10.37 kmpl', '18.59 kmpl', '9.74 kmpl',
       '14.81 kmpl', '8.2 kmpl', '12.97 kmpl', '7.5 kmpl', '30.46 km/kg',
       '6.4 kmpl', '12.85 kmpl', '18.69 kmpl', '17.24 kmpl'], dtype=object)

In [18]:
def clean_mileag (x):
    if type(x) == float :
        return np.nan
    if ' km/kg' in x :
        x = x.replace(' km/kg','')
        return float(x) * 1.35
    if  ' kmpl' in x :
        x = x.replace(' kmpl','')
        return float(x)
    return (x)

In [19]:
df['Mileage'] =  df['Mileage'].apply(clean_mileag)

In [20]:
df

,Name,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,engine_capacity(cc),Power_bhp,Seats,New_Price,Price
0,Maruti Wagon R LXI CNG,Mumbai,2010,72000,CNG,Manual,First,35.91,998,58.16,5.0,NaN,1.75
1,Hyundai Creta 1.6 CRDi SX Option,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5.0,NaN,12.50
2,Honda Jazz V,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.70,5.0,8.61 Lakh,4.50
3,Maruti Ertiga VDI,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,NaN,6.00
4,Audi A4 New 2.0 TDI Multitronic,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5.0,NaN,17.74
...,...,...,...,...,...,...,...,...,...,...,...,...,...
6014,Maruti Swift VDI,Delhi,2014,27365,Diesel,Manual,First,28.40,1248,74.00,5.0,7.88 Lakh,4.75
6015,Hyundai Xcent 1.1 CRDi S,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120,71.00,5.0,NaN,4.00
6016,Mahindra Xylo D4 BSIV,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498,112.00,8.0,NaN,2.90
6017,Maruti Wagon R VXI,Kolkata,2013,46000,Petrol,Manual,First,18.90,998,67.10,5.0,NaN,2.65
6018,Chevrolet Beat Diesel,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.60,5.0,NaN,2.50

In [21]:
df.isna().mean().round(2)*100

Name                    0.0
Location                0.0
Year                    0.0
Kilometers_Driven       0.0
Fuel_Type               0.0
Transmission            0.0
Owner_Type              0.0
Mileage                 0.0
engine_capacity(cc)     0.0
Power_bhp               2.0
Seats                   0.0
New_Price              86.0
Price                   0.0
dtype: float64

In [22]:
df.drop('New_Price',axis=1 , inplace=True)

In [23]:
d_indx = df[df['Kilometers_Driven'] == df['Kilometers_Driven'].max()].index
df.drop(d_indx , inplace=True)
df.reset_index(inplace=True,drop=True)

In [24]:
df.dropna(subset='Power_bhp' ,inplace=True ,ignore_index=True )

In [25]:
df.isna().sum()

Name                   0
Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                2
engine_capacity(cc)    0
Power_bhp              0
Seats                  0
Price                  0
dtype: int64

In [26]:
drop_indices = df[df['Mileage'] == 0].index

df.drop(drop_indices, axis= 0, inplace= True)

df.reset_index(inplace= True, drop= True)

In [27]:
df['Brand_name']= df['Name'].str.split().str[0]

In [28]:
df['Model_name']= df['Name'].str.split().str[1]

In [29]:
df.drop('Name' ,  axis=1 , inplace= True)

In [30]:
df.drop_duplicates(inplace=True ,  ignore_index=True)

In [31]:
df.head()

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,engine_capacity(cc),Power_bhp,Seats,Price,Brand_name,Model_name
0,Mumbai,2010,72000,CNG,Manual,First,35.91,998,58.16,5.0,1.75,Maruti,Wagon
1,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5.0,12.50,Hyundai,Creta
2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.70,5.0,4.50,Honda,Jazz
3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00,Maruti,Ertiga
4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5.0,17.74,Audi,A4

In [32]:
df.isna().sum()

Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                2
engine_capacity(cc)    0
Power_bhp              0
Seats                  0
Price                  0
Brand_name             0
Model_name             0
dtype: int64

In [33]:
df.shape

(5839, 13)

In [34]:
df.dropna(inplace=True)

In [35]:
df.isna().sum()
df.reset_index(inplace=True , drop=True)

In [36]:
df.isna().sum()

Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                0
engine_capacity(cc)    0
Power_bhp              0
Seats                  0
Price                  0
Brand_name             0
Model_name             0
dtype: int64

In [37]:
df.shape

(5837, 13)

### Data preprocessing for ML with Pipeline

In [38]:
x = df.drop('Price' ,axis=1)
y = df['Price']

In [39]:
x.isna().sum()

Location               0
Year                   0
Kilometers_Driven      0
Fuel_Type              0
Transmission           0
Owner_Type             0
Mileage                0
engine_capacity(cc)    0
Power_bhp              0
Seats                  0
Brand_name             0
Model_name             0
dtype: int64

In [40]:
num_col = x.select_dtypes('number').columns
num_col

Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')

### numrical Pipeline

In [41]:
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import Pipeline 

sc = StandardScaler()

num_pipeline = Pipeline(steps=[('Scaling' , sc)])
num_pipeline

Pipeline(steps=[('Scaling', StandardScaler())])

In [42]:
x.select_dtypes('object').isna().sum()

Location        0
Fuel_Type       0
Transmission    0
Owner_Type      0
Brand_name      0
Model_name      0
dtype: int64

## Categorical Pipeline
#### One Pipeline == 'Fuel_Type' ,'Transmission'
### BE Pipeline == 'Location' ,'Brand_name' , 'Model_name'
### ordinal Pipeline == 'Owner_Type'

In [43]:
nominal_col = x.select_dtypes('object').drop('Owner_Type',axis=1).columns
nominal_col

Index(['Location', 'Fuel_Type', 'Transmission', 'Brand_name', 'Model_name'], dtype='object')

In [44]:
for co in nominal_col: 
    print(co)
    print(df[co].nunique())

Location
11
Fuel_Type
4
Transmission
2
Brand_name
30
Model_name
201

In [45]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.pipeline import Pipeline 

one = OneHotEncoder(drop='first' , sparse_output= False)

one_pipline = Pipeline(steps=[('Encoding one hot' , one)])
one_pipline

Pipeline(steps=[('Encoding one hot',
                 OneHotEncoder(drop='first', sparse_output=False))])

In [46]:
from category_encoders import BinaryEncoder
from sklearn.pipeline import Pipeline 

bin = BinaryEncoder()

bin_pipeline = Pipeline(steps=[('bin_encodeing' , bin)])

bin_pipeline

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\externals\_numpydoc\docscrape.py:420: UserWarning: Unknown section Example
  self[section] = content

Pipeline(steps=[('bin_encodeing', BinaryEncoder())])

In [47]:
x['Owner_Type'].unique()

array(['First', 'Second', 'Fourth & Above', 'Third'], dtype=object)

In [48]:
from sklearn.preprocessing import OrdinalEncoder 
from sklearn.pipeline import Pipeline 

ord = OrdinalEncoder(categories=[['Fourth & Above', 'Third', 'Second' ,'First']])

ord_pipeline = Pipeline(steps=[('ordinal_pip', ord)])

ord_pipeline

Pipeline(steps=[('ordinal_pip',
                 OrdinalEncoder(categories=[['Fourth & Above', 'Third',
                                             'Second', 'First']]))])

In [49]:
print(num_col)
print(type(num_col))

Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')
<class 'pandas.core.indexes.base.Index'>

In [50]:
from sklearn.compose import ColumnTransformer 

preprocessing = ColumnTransformer([('numric', num_pipeline, num_col),
                                    ('one hot enc', one_pipline , ['Fuel_Type' ,'Transmission']),
                                    ('binary enc', bin_pipeline , ['Location' ,'Brand_name' , 'Model_name']),
                                    ('ordinal enc', ord_pipeline , ['Owner_Type'])
                                    ])

### Assign each columns to the corresponding Pipeline

In [51]:
preprocessing

ColumnTransformer(transformers=[('numric',
                                 Pipeline(steps=[('Scaling',
                                                  StandardScaler())]),
                                 Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')),
                                ('one hot enc',
                                 Pipeline(steps=[('Encoding one hot',
                                                  OneHotEncoder(drop='first',
                                                                sparse_output=False))]),
                                 ['Fuel_Type', 'Transmission']),
                                ('binary enc',
                                 Pipeline(steps=[('bin_encodeing',
                                                  BinaryEncoder())]),
                                 ['Location', 'Brand_name', 'Model_name']),
                                ('ordinal enc',
                                 Pipeline(steps=[('ordinal_pip',
                                                  OrdinalEncoder(categories=[['Fourth '
                                                                              '& '
                                                                              'Above',
                                                                              'Third',
                                                                              'Second',
                                                                              'First']]))]),
                                 ['Owner_Type'])])

In [49]:
from sklearn.ensemble import RandomForestRegressor

In [50]:
from sklearn.linear_model import LinearRegression ,  SGDRegressor , ElasticNet , Lasso , Ridge
from sklearn.neighbors import KNeighborsRegressor
from sklearn.preprocessing import PolynomialFeatures
from sklearn.model_selection import cross_validate 
from sklearn.model_selection import KFold
from sklearn.svm import SVR
from sklearn.tree import DecisionTreeRegressor 
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRFRegressor
from catboost import CatBoostRegressor
from lightgbm import LGBMRegressor 

models = [ ('linear', LinearRegression()) ,
        #   ('SGDRegressord' , SGDRegressor(random_state=42)) ,
          ('poly' ,  PolynomialFeatures(degree=2)),
        #   ('elastic' , ElasticNet(random_state=42))  , 
        #  ('lasso', Lasso(random_state=42)), 
          ('knn', KNeighborsRegressor(n_neighbors=5)),
          ('svm', SVR(kernel='linear')),
          ('DT', DecisionTreeRegressor(random_state=42)), 
          ('RF', RandomForestRegressor(random_state=42 , n_jobs= -1)),
          ('xgboost', XGBRFRegressor(random_state=42 , n_jobs= -1)),
          ('catboost', CatBoostRegressor(random_state=42)),
          ('lightgbm', LGBMRegressor(random_state=42 , n_jobs= -1)) 
          ]

for model in models : 

    model_pip = Pipeline(steps= [('preprocessing' , preprocessing) , ('models' , model[1])])

    if model[0] == 'poly':
        model_pip = Pipeline(steps=[('preprocessing' , preprocessing ), ('poly' , PolynomialFeatures()) , ('model' , Ridge())])

    cvs = cross_validate(estimator= model_pip , X=x , y= y , cv= 5 , scoring= 'r2' ,return_train_score=True)
    print(model[0])
    print( 'Train_score R2 ',round(cvs['train_score'].mean()*100, 2))
    print( 'Test_score R2 ',round(cvs['test_score'].mean()*100, 2))
    print( 'Fit_time  ',round(cvs['fit_time'].mean(), 4))
    print('\n', 100*'=' )

linear
Train_score R2  72.41
Test_score R2  71.74
Fit_time   0.0705

 ====================================================================================================
poly
Train_score R2  92.9
Test_score R2  88.37
Fit_time   0.1276

 ====================================================================================================
knn
Train_score R2  93.05
Test_score R2  87.27
Fit_time   0.0582

 ====================================================================================================
svm
Train_score R2  66.72
Test_score R2  66.42
Fit_time   1.3573

 ====================================================================================================
DT
Train_score R2  100.0
Test_score R2  80.99
Fit_time   0.108

 ====================================================================================================
RF
Train_score R2  98.42
Test_score R2  88.24
Fit_time   0.7329

 ====================================================================================================
xgboost
Train_score R2  92.35
Test_score R2  85.22
Fit_time   0.2922

 ====================================================================================================
Learning rate set to 0.05223
0:	learn: 10.6796028	total: 147ms	remaining: 2m 27s
1:	learn: 10.3004837	total: 151ms	remaining: 1m 15s
2:	learn: 9.9241611	total: 155ms	remaining: 51.5s
3:	learn: 9.5979175	total: 158ms	remaining: 39.3s
4:	learn: 9.2575153	total: 161ms	remaining: 32.1s
5:	learn: 8.9513756	total: 165ms	remaining: 27.3s
6:	learn: 8.6872213	total: 168ms	remaining: 23.8s
7:	learn: 8.4244774	total: 171ms	remaining: 21.2s
8:	learn: 8.1707130	total: 174ms	remaining: 19.2s
9:	learn: 7.9133274	total: 178ms	remaining: 17.6s
10:	learn: 7.6798954	total: 181ms	remaining: 16.3s
11:	learn: 7.4677430	total: 184ms	remaining: 15.1s
12:	learn: 7.2498691	total: 187ms	remaining: 14.2s
13:	learn: 7.0550676	total: 191ms	remaining: 13.4s
14:	learn: 6.8726481	total: 194ms	remaining: 12.7s
15:	learn: 6.6942664	total: 197ms	remaining: 12.1s
16:	learn: 6.5321681	total: 200ms	remaining: 11.6s
17:	learn: 6.3678047	total: 203ms	remaining: 11.1s
18:	learn: 6.2168207	total: 206ms	remaining: 10.6s
19:	learn: 6.0788785	total: 209ms	remaining: 10.3s
20:	learn: 5.9450065	total: 212ms	remaining: 9.91s
21:	learn: 5.8221495	total: 216ms	remaining: 9.58s
22:	learn: 5.7084672	total: 219ms	remaining: 9.29s
23:	learn: 5.5947034	total: 222ms	remaining: 9.03s
24:	learn: 5.4903551	total: 226ms	remaining: 8.79s
25:	learn: 5.3896727	total: 229ms	remaining: 8.56s
26:	learn: 5.2798224	total: 232ms	remaining: 8.35s
27:	learn: 5.1865806	total: 235ms	remaining: 8.15s
28:	learn: 5.1012538	total: 238ms	remaining: 7.98s
29:	learn: 5.0057797	total: 242ms	remaining: 7.82s
30:	learn: 4.9232689	total: 245ms	remaining: 7.66s
31:	learn: 4.8499523	total: 248ms	remaining: 7.51s
32:	learn: 4.7744452	total: 251ms	remaining: 7.37s
33:	learn: 4.7043097	total: 257ms	remaining: 7.29s
34:	learn: 4.6433667	total: 260ms	remaining: 7.17s
35:	learn: 4.5815363	total: 263ms	remaining: 7.05s
36:	learn: 4.5208124	total: 266ms	remaining: 6.93s
37:	learn: 4.4657568	total: 270ms	remaining: 6.84s
38:	learn: 4.4181532	total: 274ms	remaining: 6.74s
39:	learn: 4.3594768	total: 277ms	remaining: 6.64s
40:	learn: 4.3144085	total: 280ms	remaining: 6.54s
41:	learn: 4.2618155	total: 283ms	remaining: 6.46s
42:	learn: 4.2213322	total: 286ms	remaining: 6.37s
43:	learn: 4.1796932	total: 290ms	remaining: 6.29s
44:	learn: 4.1349821	total: 293ms	remaining: 6.21s
45:	learn: 4.0918952	total: 296ms	remaining: 6.14s
46:	learn: 4.0540534	total: 300ms	remaining: 6.08s
47:	learn: 4.0097222	total: 303ms	remaining: 6.02s
48:	learn: 3.9750013	total: 307ms	remaining: 5.95s
49:	learn: 3.9412126	total: 310ms	remaining: 5.89s
50:	learn: 3.9131092	total: 313ms	remaining: 5.83s
51:	learn: 3.8771877	total: 317ms	remaining: 5.79s
52:	learn: 3.8489496	total: 321ms	remaining: 5.74s
53:	learn: 3.8219667	total: 325ms	remaining: 5.68s
54:	learn: 3.7925220	total: 328ms	remaining: 5.63s
55:	learn: 3.7629267	total: 332ms	remaining: 5.59s
56:	learn: 3.7343551	total: 335ms	remaining: 5.54s
57:	learn: 3.7083180	total: 338ms	remaining: 5.5s
58:	learn: 3.6837054	total: 342ms	remaining: 5.45s
59:	learn: 3.6623192	total: 346ms	remaining: 5.42s
60:	learn: 3.6430586	total: 350ms	remaining: 5.38s
61:	learn: 3.6230169	total: 353ms	remaining: 5.33s
62:	learn: 3.5994733	total: 355ms	remaining: 5.29s
63:	learn: 3.5833052	total: 358ms	remaining: 5.24s
64:	learn: 3.5654269	total: 363ms	remaining: 5.22s
65:	learn: 3.5504523	total: 366ms	remaining: 5.18s
66:	learn: 3.5277290	total: 369ms	remaining: 5.14s
67:	learn: 3.5120140	total: 372ms	remaining: 5.11s
68:	learn: 3.4890259	total: 376ms	remaining: 5.07s
69:	learn: 3.4759024	total: 379ms	remaining: 5.03s
70:	learn: 3.4611925	total: 382ms	remaining: 5s
71:	learn: 3.4515873	total: 385ms	remaining: 4.96s
72:	learn: 3.4358344	total: 388ms	remaining: 4.93s
73:	learn: 3.4237327	total: 392ms	remaining: 4.9s
74:	learn: 3.4149374	total: 395ms	remaining: 4.87s
75:	learn: 3.3987136	total: 398ms	remaining: 4.84s
76:	learn: 3.3803385	total: 401ms	remaining: 4.81s
77:	learn: 3.3683778	total: 404ms	remaining: 4.78s
78:	learn: 3.3454345	total: 407ms	remaining: 4.75s
79:	learn: 3.3351823	total: 411ms	remaining: 4.72s
80:	learn: 3.3196908	total: 414ms	remaining: 4.7s
81:	learn: 3.3081985	total: 417ms	remaining: 4.67s
82:	learn: 3.2940987	total: 420ms	remaining: 4.64s
83:	learn: 3.2812047	total: 423ms	remaining: 4.62s
84:	learn: 3.2668176	total: 427ms	remaining: 4.6s
85:	learn: 3.2551371	total: 430ms	remaining: 4.57s
86:	learn: 3.2478821	total: 434ms	remaining: 4.55s
87:	learn: 3.2460683	total: 436ms	remaining: 4.51s
88:	learn: 3.2313624	total: 439ms	remaining: 4.49s
89:	learn: 3.2261258	total: 442ms	remaining: 4.47s
90:	learn: 3.2100544	total: 445ms	remaining: 4.45s
91:	learn: 3.1994386	total: 449ms	remaining: 4.43s
92:	learn: 3.1893807	total: 452ms	remaining: 4.4s
93:	learn: 3.1772979	total: 455ms	remaining: 4.38s
94:	learn: 3.1672044	total: 458ms	remaining: 4.36s
95:	learn: 3.1596785	total: 461ms	remaining: 4.34s
96:	learn: 3.1480913	total: 464ms	remaining: 4.32s
97:	learn: 3.1405819	total: 468ms	remaining: 4.3s
98:	learn: 3.1338723	total: 471ms	remaining: 4.29s
99:	learn: 3.1264012	total: 475ms	remaining: 4.27s
100:	learn: 3.1224035	total: 478ms	remaining: 4.25s
101:	learn: 3.1099368	total: 481ms	remaining: 4.24s
102:	learn: 3.1022442	total: 484ms	remaining: 4.22s
103:	learn: 3.0905671	total: 488ms	remaining: 4.2s
104:	learn: 3.0727925	total: 491ms	remaining: 4.18s
105:	learn: 3.0646614	total: 494ms	remaining: 4.17s
106:	learn: 3.0528109	total: 497ms	remaining: 4.15s
107:	learn: 3.0398010	total: 501ms	remaining: 4.13s
108:	learn: 3.0341683	total: 504ms	remaining: 4.12s
109:	learn: 3.0227629	total: 507ms	remaining: 4.1s
110:	learn: 3.0183117	total: 510ms	remaining: 4.09s
111:	learn: 3.0084901	total: 513ms	remaining: 4.07s
112:	learn: 2.9994507	total: 517ms	remaining: 4.06s
113:	learn: 2.9886404	total: 521ms	remaining: 4.04s
114:	learn: 2.9712458	total: 524ms	remaining: 4.03s
115:	learn: 2.9612262	total: 527ms	remaining: 4.01s
116:	learn: 2.9583691	total: 530ms	remaining: 4s
117:	learn: 2.9525164	total: 534ms	remaining: 3.99s
118:	learn: 2.9467346	total: 538ms	remaining: 3.98s
119:	learn: 2.9389406	total: 541ms	remaining: 3.97s
120:	learn: 2.9283451	total: 544ms	remaining: 3.95s
121:	learn: 2.9246938	total: 548ms	remaining: 3.94s
122:	learn: 2.9136079	total: 551ms	remaining: 3.93s
123:	learn: 2.9023404	total: 554ms	remaining: 3.91s
124:	learn: 2.8915121	total: 557ms	remaining: 3.9s
125:	learn: 2.8873210	total: 560ms	remaining: 3.88s
126:	learn: 2.8809552	total: 563ms	remaining: 3.87s
127:	learn: 2.8731111	total: 566ms	remaining: 3.86s
128:	learn: 2.8656658	total: 569ms	remaining: 3.84s
129:	learn: 2.8533383	total: 572ms	remaining: 3.83s
130:	learn: 2.8458049	total: 575ms	remaining: 3.82s
131:	learn: 2.8396424	total: 579ms	remaining: 3.81s
132:	learn: 2.8279530	total: 582ms	remaining: 3.79s
133:	learn: 2.8096889	total: 585ms	remaining: 3.78s
134:	learn: 2.8017550	total: 589ms	remaining: 3.77s
135:	learn: 2.7903736	total: 592ms	remaining: 3.76s
136:	learn: 2.7817066	total: 595ms	remaining: 3.75s
137:	learn: 2.7770335	total: 598ms	remaining: 3.74s
138:	learn: 2.7727746	total: 602ms	remaining: 3.73s
139:	learn: 2.7662287	total: 605ms	remaining: 3.71s
140:	learn: 2.7632813	total: 608ms	remaining: 3.7s
141:	learn: 2.7545386	total: 611ms	remaining: 3.69s
142:	learn: 2.7488733	total: 615ms	remaining: 3.68s
143:	learn: 2.7401619	total: 618ms	remaining: 3.67s
144:	learn: 2.7305838	total: 621ms	remaining: 3.66s
145:	learn: 2.7248834	total: 624ms	remaining: 3.65s
146:	learn: 2.7206053	total: 628ms	remaining: 3.64s
147:	learn: 2.7158443	total: 631ms	remaining: 3.63s
148:	learn: 2.7099161	total: 634ms	remaining: 3.62s
149:	learn: 2.7060025	total: 637ms	remaining: 3.61s
150:	learn: 2.6970733	total: 640ms	remaining: 3.6s
151:	learn: 2.6924480	total: 643ms	remaining: 3.59s
152:	learn: 2.6880958	total: 646ms	remaining: 3.58s
153:	learn: 2.6764006	total: 650ms	remaining: 3.57s
154:	learn: 2.6674461	total: 653ms	remaining: 3.56s
155:	learn: 2.6594965	total: 656ms	remaining: 3.55s
156:	learn: 2.6550147	total: 659ms	remaining: 3.54s
157:	learn: 2.6503294	total: 662ms	remaining: 3.53s
158:	learn: 2.6426659	total: 666ms	remaining: 3.52s
159:	learn: 2.6354332	total: 669ms	remaining: 3.51s
160:	learn: 2.6252307	total: 672ms	remaining: 3.5s
161:	learn: 2.6200082	total: 675ms	remaining: 3.49s
162:	learn: 2.6096847	total: 678ms	remaining: 3.48s
163:	learn: 2.6019142	total: 682ms	remaining: 3.47s
164:	learn: 2.5953153	total: 685ms	remaining: 3.46s
165:	learn: 2.5923776	total: 688ms	remaining: 3.46s
166:	learn: 2.5895135	total: 691ms	remaining: 3.45s
167:	learn: 2.5821419	total: 695ms	remaining: 3.44s
168:	learn: 2.5790690	total: 698ms	remaining: 3.43s
169:	learn: 2.5767591	total: 701ms	remaining: 3.42s
170:	learn: 2.5690482	total: 705ms	remaining: 3.42s
171:	learn: 2.5633356	total: 708ms	remaining: 3.41s
172:	learn: 2.5547394	total: 711ms	remaining: 3.4s
173:	learn: 2.5512420	total: 715ms	remaining: 3.39s
174:	learn: 2.5417107	total: 718ms	remaining: 3.38s
175:	learn: 2.5369372	total: 721ms	remaining: 3.38s
176:	learn: 2.5300759	total: 724ms	remaining: 3.37s
177:	learn: 2.5272657	total: 727ms	remaining: 3.36s
178:	learn: 2.5178562	total: 730ms	remaining: 3.35s
179:	learn: 2.5119981	total: 734ms	remaining: 3.35s
180:	learn: 2.5093846	total: 737ms	remaining: 3.33s
181:	learn: 2.5040065	total: 740ms	remaining: 3.33s
182:	learn: 2.4924590	total: 744ms	remaining: 3.32s
183:	learn: 2.4879576	total: 747ms	remaining: 3.31s
184:	learn: 2.4836731	total: 751ms	remaining: 3.31s
185:	learn: 2.4794525	total: 754ms	remaining: 3.3s
186:	learn: 2.4704253	total: 757ms	remaining: 3.29s
187:	learn: 2.4672635	total: 761ms	remaining: 3.29s
188:	learn: 2.4613277	total: 764ms	remaining: 3.28s
189:	learn: 2.4528523	total: 768ms	remaining: 3.27s
190:	learn: 2.4448673	total: 771ms	remaining: 3.26s
191:	learn: 2.4365382	total: 774ms	remaining: 3.26s
192:	learn: 2.4298994	total: 777ms	remaining: 3.25s
193:	learn: 2.4230728	total: 780ms	remaining: 3.24s
194:	learn: 2.4167447	total: 784ms	remaining: 3.24s
195:	learn: 2.4100525	total: 787ms	remaining: 3.23s
196:	learn: 2.4024423	total: 790ms	remaining: 3.22s
197:	learn: 2.3970816	total: 793ms	remaining: 3.21s
198:	learn: 2.3919051	total: 797ms	remaining: 3.21s
199:	learn: 2.3856900	total: 800ms	remaining: 3.2s
200:	learn: 2.3771630	total: 803ms	remaining: 3.19s
201:	learn: 2.3752445	total: 807ms	remaining: 3.19s
202:	learn: 2.3676196	total: 810ms	remaining: 3.18s
203:	learn: 2.3623618	total: 813ms	remaining: 3.17s
204:	learn: 2.3605413	total: 816ms	remaining: 3.17s
205:	learn: 2.3538426	total: 820ms	remaining: 3.16s
206:	learn: 2.3476667	total: 823ms	remaining: 3.15s
207:	learn: 2.3428130	total: 826ms	remaining: 3.14s
208:	learn: 2.3369796	total: 829ms	remaining: 3.14s
209:	learn: 2.3352655	total: 832ms	remaining: 3.13s
210:	learn: 2.3336206	total: 835ms	remaining: 3.12s
211:	learn: 2.3277448	total: 839ms	remaining: 3.12s
212:	learn: 2.3261837	total: 842ms	remaining: 3.11s
213:	learn: 2.3216257	total: 846ms	remaining: 3.11s
214:	learn: 2.3165744	total: 849ms	remaining: 3.1s
215:	learn: 2.3122667	total: 852ms	remaining: 3.09s
216:	learn: 2.3046460	total: 855ms	remaining: 3.09s
217:	learn: 2.3008418	total: 859ms	remaining: 3.08s
218:	learn: 2.2958027	total: 863ms	remaining: 3.08s
219:	learn: 2.2900674	total: 866ms	remaining: 3.07s
220:	learn: 2.2885682	total: 869ms	remaining: 3.06s
221:	learn: 2.2871281	total: 873ms	remaining: 3.06s
222:	learn: 2.2857444	total: 876ms	remaining: 3.05s
223:	learn: 2.2820053	total: 879ms	remaining: 3.05s
224:	learn: 2.2804094	total: 882ms	remaining: 3.04s
225:	learn: 2.2794720	total: 885ms	remaining: 3.03s
226:	learn: 2.2724332	total: 889ms	remaining: 3.03s
227:	learn: 2.2671895	total: 892ms	remaining: 3.02s
228:	learn: 2.2637359	total: 896ms	remaining: 3.02s
229:	learn: 2.2536751	total: 899ms	remaining: 3.01s
230:	learn: 2.2520981	total: 902ms	remaining: 3s
231:	learn: 2.2461343	total: 906ms	remaining: 3s
232:	learn: 2.2452938	total: 909ms	remaining: 2.99s
233:	learn: 2.2395600	total: 912ms	remaining: 2.98s
234:	learn: 2.2347314	total: 915ms	remaining: 2.98s
235:	learn: 2.2294330	total: 918ms	remaining: 2.97s
236:	learn: 2.2216267	total: 921ms	remaining: 2.96s
237:	learn: 2.2173273	total: 924ms	remaining: 2.96s
238:	learn: 2.2134291	total: 927ms	remaining: 2.95s
239:	learn: 2.2065736	total: 931ms	remaining: 2.95s
240:	learn: 2.1993071	total: 935ms	remaining: 2.94s
241:	learn: 2.1910475	total: 938ms	remaining: 2.94s
242:	learn: 2.1864222	total: 941ms	remaining: 2.93s
243:	learn: 2.1815051	total: 944ms	remaining: 2.92s
244:	learn: 2.1758813	total: 947ms	remaining: 2.92s
245:	learn: 2.1751481	total: 951ms	remaining: 2.92s
246:	learn: 2.1709494	total: 954ms	remaining: 2.91s
247:	learn: 2.1687502	total: 958ms	remaining: 2.9s
248:	learn: 2.1637129	total: 961ms	remaining: 2.9s
249:	learn: 2.1582572	total: 964ms	remaining: 2.89s
250:	learn: 2.1536682	total: 968ms	remaining: 2.89s
251:	learn: 2.1455086	total: 971ms	remaining: 2.88s
252:	learn: 2.1399028	total: 974ms	remaining: 2.88s
253:	learn: 2.1367908	total: 977ms	remaining: 2.87s
254:	learn: 2.1340919	total: 980ms	remaining: 2.86s
255:	learn: 2.1308479	total: 983ms	remaining: 2.86s
256:	learn: 2.1281978	total: 987ms	remaining: 2.85s
257:	learn: 2.1247538	total: 990ms	remaining: 2.85s
258:	learn: 2.1240706	total: 993ms	remaining: 2.84s
259:	learn: 2.1160753	total: 996ms	remaining: 2.83s
260:	learn: 2.1109716	total: 1000ms	remaining: 2.83s
261:	learn: 2.1041268	total: 1s	remaining: 2.82s
262:	learn: 2.0952393	total: 1.01s	remaining: 2.82s
263:	learn: 2.0877669	total: 1.01s	remaining: 2.81s
264:	learn: 2.0832392	total: 1.01s	remaining: 2.81s
265:	learn: 2.0821690	total: 1.01s	remaining: 2.8s
266:	learn: 2.0785730	total: 1.02s	remaining: 2.8s
267:	learn: 2.0719468	total: 1.02s	remaining: 2.79s
268:	learn: 2.0707595	total: 1.02s	remaining: 2.78s
269:	learn: 2.0697638	total: 1.03s	remaining: 2.78s
270:	learn: 2.0639852	total: 1.03s	remaining: 2.77s
271:	learn: 2.0619667	total: 1.03s	remaining: 2.77s
272:	learn: 2.0590459	total: 1.04s	remaining: 2.76s
273:	learn: 2.0581006	total: 1.04s	remaining: 2.76s
274:	learn: 2.0529147	total: 1.04s	remaining: 2.75s
275:	learn: 2.0500867	total: 1.05s	remaining: 2.75s
276:	learn: 2.0491693	total: 1.05s	remaining: 2.74s
277:	learn: 2.0437062	total: 1.05s	remaining: 2.73s
278:	learn: 2.0398371	total: 1.06s	remaining: 2.73s
279:	learn: 2.0380084	total: 1.06s	remaining: 2.73s
280:	learn: 2.0341575	total: 1.06s	remaining: 2.72s
281:	learn: 2.0282587	total: 1.07s	remaining: 2.71s
282:	learn: 2.0223529	total: 1.07s	remaining: 2.71s
283:	learn: 2.0202582	total: 1.07s	remaining: 2.7s
284:	learn: 2.0176766	total: 1.08s	remaining: 2.7s
285:	learn: 2.0107636	total: 1.08s	remaining: 2.7s
286:	learn: 2.0043724	total: 1.08s	remaining: 2.69s
287:	learn: 2.0006607	total: 1.09s	remaining: 2.69s
288:	learn: 1.9973205	total: 1.09s	remaining: 2.68s
289:	learn: 1.9925592	total: 1.09s	remaining: 2.68s
290:	learn: 1.9889788	total: 1.1s	remaining: 2.67s
291:	learn: 1.9852708	total: 1.1s	remaining: 2.67s
292:	learn: 1.9824228	total: 1.1s	remaining: 2.66s
293:	learn: 1.9773314	total: 1.11s	remaining: 2.66s
294:	learn: 1.9735488	total: 1.11s	remaining: 2.65s
295:	learn: 1.9721449	total: 1.11s	remaining: 2.65s
296:	learn: 1.9664217	total: 1.11s	remaining: 2.64s
297:	learn: 1.9610529	total: 1.12s	remaining: 2.64s
298:	learn: 1.9602131	total: 1.12s	remaining: 2.63s
299:	learn: 1.9572322	total: 1.13s	remaining: 2.63s
300:	learn: 1.9519593	total: 1.13s	remaining: 2.62s
301:	learn: 1.9500583	total: 1.13s	remaining: 2.62s
302:	learn: 1.9448615	total: 1.14s	remaining: 2.62s
303:	learn: 1.9398796	total: 1.14s	remaining: 2.61s
304:	learn: 1.9354687	total: 1.14s	remaining: 2.61s
305:	learn: 1.9349399	total: 1.15s	remaining: 2.6s
306:	learn: 1.9322357	total: 1.15s	remaining: 2.6s
307:	learn: 1.9292299	total: 1.15s	remaining: 2.59s
308:	learn: 1.9270776	total: 1.16s	remaining: 2.59s
309:	learn: 1.9255400	total: 1.16s	remaining: 2.58s
310:	learn: 1.9209022	total: 1.16s	remaining: 2.58s
311:	learn: 1.9163457	total: 1.17s	remaining: 2.57s
312:	learn: 1.9135613	total: 1.17s	remaining: 2.57s
313:	learn: 1.9080357	total: 1.17s	remaining: 2.56s
314:	learn: 1.9028931	total: 1.18s	remaining: 2.56s
315:	learn: 1.8985801	total: 1.18s	remaining: 2.56s
316:	learn: 1.8975102	total: 1.18s	remaining: 2.55s
317:	learn: 1.8933378	total: 1.19s	remaining: 2.55s
318:	learn: 1.8928577	total: 1.19s	remaining: 2.54s
319:	learn: 1.8907989	total: 1.19s	remaining: 2.54s
320:	learn: 1.8886796	total: 1.2s	remaining: 2.53s
321:	learn: 1.8843161	total: 1.2s	remaining: 2.53s
322:	learn: 1.8821322	total: 1.2s	remaining: 2.52s
323:	learn: 1.8779099	total: 1.21s	remaining: 2.52s
324:	learn: 1.8774536	total: 1.21s	remaining: 2.51s
325:	learn: 1.8729522	total: 1.21s	remaining: 2.51s
326:	learn: 1.8684889	total: 1.22s	remaining: 2.51s
327:	learn: 1.8645226	total: 1.22s	remaining: 2.5s
328:	learn: 1.8637131	total: 1.22s	remaining: 2.5s
329:	learn: 1.8595912	total: 1.23s	remaining: 2.49s
330:	learn: 1.8589855	total: 1.23s	remaining: 2.49s
331:	learn: 1.8566795	total: 1.23s	remaining: 2.48s
332:	learn: 1.8551225	total: 1.24s	remaining: 2.48s
333:	learn: 1.8520835	total: 1.24s	remaining: 2.47s
334:	learn: 1.8504025	total: 1.24s	remaining: 2.47s
335:	learn: 1.8480256	total: 1.25s	remaining: 2.46s
336:	learn: 1.8442964	total: 1.25s	remaining: 2.46s
337:	learn: 1.8407277	total: 1.25s	remaining: 2.45s
338:	learn: 1.8356767	total: 1.25s	remaining: 2.45s
339:	learn: 1.8351248	total: 1.26s	remaining: 2.44s
340:	learn: 1.8314798	total: 1.26s	remaining: 2.44s
341:	learn: 1.8288725	total: 1.26s	remaining: 2.44s
342:	learn: 1.8267043	total: 1.27s	remaining: 2.43s
343:	learn: 1.8220570	total: 1.27s	remaining: 2.42s
344:	learn: 1.8205108	total: 1.27s	remaining: 2.42s
345:	learn: 1.8179248	total: 1.28s	remaining: 2.42s
346:	learn: 1.8175541	total: 1.28s	remaining: 2.41s
347:	learn: 1.8148710	total: 1.28s	remaining: 2.41s
348:	learn: 1.8129443	total: 1.29s	remaining: 2.4s
349:	learn: 1.8106782	total: 1.29s	remaining: 2.4s
350:	learn: 1.8082396	total: 1.29s	remaining: 2.39s
351:	learn: 1.8056289	total: 1.3s	remaining: 2.39s
352:	learn: 1.8017103	total: 1.3s	remaining: 2.38s
353:	learn: 1.8008001	total: 1.3s	remaining: 2.38s
354:	learn: 1.7991687	total: 1.31s	remaining: 2.38s
355:	learn: 1.7981185	total: 1.31s	remaining: 2.37s
356:	learn: 1.7946022	total: 1.31s	remaining: 2.37s
357:	learn: 1.7903094	total: 1.32s	remaining: 2.36s
358:	learn: 1.7860159	total: 1.32s	remaining: 2.36s
359:	learn: 1.7819340	total: 1.32s	remaining: 2.36s
360:	learn: 1.7778055	total: 1.33s	remaining: 2.35s
361:	learn: 1.7753250	total: 1.33s	remaining: 2.35s
362:	learn: 1.7727999	total: 1.33s	remaining: 2.34s
363:	learn: 1.7691028	total: 1.34s	remaining: 2.34s

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000466 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 929
[LightGBM] [Info] Number of data points in the train set: 4669, number of used features: 27
[LightGBM] [Info] Start training from score 9.542163

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000477 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 929
[LightGBM] [Info] Number of data points in the train set: 4670, number of used features: 27
[LightGBM] [Info] Start training from score 9.614625

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000455 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 928
[LightGBM] [Info] Number of data points in the train set: 4670, number of used features: 27
[LightGBM] [Info] Start training from score 9.633208

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

[LightGBM] [Info] Auto-choosing row-wise multi-threading, the overhead of testing was 0.000487 seconds.
You can set `force_row_wise=true` to remove the overhead.
And if memory is not enough, you can set `force_col_wise=true`.
[LightGBM] [Info] Total Bins 928
[LightGBM] [Info] Number of data points in the train set: 4670, number of used features: 27
[LightGBM] [Info] Start training from score 9.538724
lightgbm
Train_score R2  96.84
Test_score R2  90.35
Fit_time   0.2391

 ====================================================================================================

c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(
c:\Users\DELL\anaconda3\envs\ai\Lib\site-packages\sklearn\utils\validation.py:2691: UserWarning: X does not have valid feature names, but LGBMRegressor was fitted with feature names
  warnings.warn(

In [52]:
from catboost import CatBoostRegressor
catboost_pipeline = Pipeline(steps=[('preprocessing' , preprocessing ), ('model' , CatBoostRegressor())])
catboost_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numric',
                                                  Pipeline(steps=[('Scaling',
                                                                   StandardScaler())]),
                                                  Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')),
                                                 ('one hot enc',
                                                  Pipeline(steps=[('Encoding '
                                                                   'one hot',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  ['Fuel_Type',
                                                   'Transmission']),
                                                 ('binary enc',
                                                  Pipeline(steps=[('bin_encodeing',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Brand_name',
                                                   'Model_name']),
                                                 ('ordinal enc',
                                                  Pipeline(steps=[('ordinal_pip',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model', CatBoostRegressor(loss_function='RMSE'))])

In [ ]:
from sklearn.model_selection import GridSearchCV 
param_grids = {
    "model__depth": [4, 5, 6, 7],
    "model__learning_rate": [0.01, 0.03, 0.05],
    "model__iterations": [1000, 1500, 2000], }

Grid_search = GridSearchCV(catboost_pipeline , param_grid=param_grids ,cv=5 , scoring='r2',return_train_score=True, n_jobs=-1 )
Grid_search.fit(x , y)

KeyboardInterrupt:

In [ ]:
Grid_search.best_params_

AttributeError: 'GridSearchCV' object has no attribute 'best_params_'

In [52]:
Grid_search.best_score_

NameError: name 'Grid_search' is not defined

In [53]:
catboost_finall_pipeline = Pipeline(steps=[('preprocessing' , preprocessing ), ('model' , CatBoostRegressor(random_state=42))])
catboost_finall_pipeline

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numric',
                                                  Pipeline(steps=[('Scaling',
                                                                   StandardScaler())]),
                                                  Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')),
                                                 ('one hot enc',
                                                  Pipeline(steps=[('Encoding '
                                                                   'one hot',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  ['Fuel_Type',
                                                   'Transmission']),
                                                 ('binary enc',
                                                  Pipeline(steps=[('bin_encodeing',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Brand_name',
                                                   'Model_name']),
                                                 ('ordinal enc',
                                                  Pipeline(steps=[('ordinal_pip',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model',
                 CatBoostRegressor(loss_function='RMSE', random_state=42))])

In [54]:
catboost_finall_pipeline.fit(x , y)

Learning rate set to 0.054105
0:	learn: 10.7460438	total: 210ms	remaining: 3m 29s
1:	learn: 10.3376775	total: 223ms	remaining: 1m 51s
2:	learn: 9.9462161	total: 237ms	remaining: 1m 18s
3:	learn: 9.5930060	total: 254ms	remaining: 1m 3s
4:	learn: 9.2408139	total: 260ms	remaining: 51.6s
5:	learn: 8.9175729	total: 268ms	remaining: 44.4s
6:	learn: 8.6176684	total: 272ms	remaining: 38.6s
7:	learn: 8.3200128	total: 277ms	remaining: 34.4s
8:	learn: 8.0630984	total: 285ms	remaining: 31.4s
9:	learn: 7.8173334	total: 292ms	remaining: 28.9s
10:	learn: 7.5745892	total: 302ms	remaining: 27.2s
11:	learn: 7.3527660	total: 308ms	remaining: 25.3s
12:	learn: 7.1235294	total: 319ms	remaining: 24.2s
13:	learn: 6.9303230	total: 324ms	remaining: 22.8s
14:	learn: 6.7372303	total: 335ms	remaining: 22s
15:	learn: 6.5593981	total: 344ms	remaining: 21.1s
16:	learn: 6.3919114	total: 351ms	remaining: 20.3s
17:	learn: 6.2317603	total: 359ms	remaining: 19.6s
18:	learn: 6.0848854	total: 367ms	remaining: 19s
19:	learn: 5.9501467	total: 372ms	remaining: 18.2s
20:	learn: 5.8082141	total: 380ms	remaining: 17.7s
21:	learn: 5.6919424	total: 385ms	remaining: 17.1s
22:	learn: 5.5813154	total: 392ms	remaining: 16.6s
23:	learn: 5.4671634	total: 398ms	remaining: 16.2s
24:	learn: 5.3468569	total: 403ms	remaining: 15.7s
25:	learn: 5.2571432	total: 411ms	remaining: 15.4s
26:	learn: 5.1483279	total: 416ms	remaining: 15s
27:	learn: 5.0604701	total: 434ms	remaining: 15.1s
28:	learn: 4.9651075	total: 442ms	remaining: 14.8s
29:	learn: 4.8881370	total: 447ms	remaining: 14.4s
30:	learn: 4.8036345	total: 455ms	remaining: 14.2s
31:	learn: 4.7341009	total: 465ms	remaining: 14.1s
32:	learn: 4.6573480	total: 487ms	remaining: 14.3s
33:	learn: 4.5866830	total: 493ms	remaining: 14s
34:	learn: 4.5283421	total: 498ms	remaining: 13.7s
35:	learn: 4.4725332	total: 504ms	remaining: 13.5s
36:	learn: 4.4114697	total: 509ms	remaining: 13.2s
37:	learn: 4.3606095	total: 513ms	remaining: 13s
38:	learn: 4.3119677	total: 521ms	remaining: 12.8s
39:	learn: 4.2531982	total: 526ms	remaining: 12.6s
40:	learn: 4.2048279	total: 533ms	remaining: 12.5s
41:	learn: 4.1550673	total: 538ms	remaining: 12.3s
42:	learn: 4.1160520	total: 542ms	remaining: 12.1s
43:	learn: 4.0716478	total: 546ms	remaining: 11.9s
44:	learn: 4.0336612	total: 552ms	remaining: 11.7s
45:	learn: 3.9946931	total: 555ms	remaining: 11.5s
46:	learn: 3.9546887	total: 560ms	remaining: 11.4s
47:	learn: 3.9250719	total: 567ms	remaining: 11.2s
48:	learn: 3.8930467	total: 571ms	remaining: 11.1s
49:	learn: 3.8659047	total: 575ms	remaining: 10.9s
50:	learn: 3.8347434	total: 581ms	remaining: 10.8s
51:	learn: 3.8135514	total: 585ms	remaining: 10.7s
52:	learn: 3.7817243	total: 591ms	remaining: 10.6s
53:	learn: 3.7578054	total: 598ms	remaining: 10.5s
54:	learn: 3.7314954	total: 603ms	remaining: 10.4s
55:	learn: 3.7017667	total: 606ms	remaining: 10.2s
56:	learn: 3.6777685	total: 615ms	remaining: 10.2s
57:	learn: 3.6540664	total: 620ms	remaining: 10.1s
58:	learn: 3.6365443	total: 624ms	remaining: 9.95s
59:	learn: 3.6163931	total: 631ms	remaining: 9.89s
60:	learn: 3.5963339	total: 636ms	remaining: 9.79s
61:	learn: 3.5652220	total: 640ms	remaining: 9.69s
62:	learn: 3.5502837	total: 646ms	remaining: 9.61s
63:	learn: 3.5372118	total: 650ms	remaining: 9.51s
64:	learn: 3.5188567	total: 654ms	remaining: 9.41s
65:	learn: 3.5081650	total: 660ms	remaining: 9.34s
66:	learn: 3.4933301	total: 664ms	remaining: 9.24s
67:	learn: 3.4838570	total: 668ms	remaining: 9.15s
68:	learn: 3.4749844	total: 674ms	remaining: 9.09s
69:	learn: 3.4575869	total: 678ms	remaining: 9.01s
70:	learn: 3.4468845	total: 682ms	remaining: 8.92s
71:	learn: 3.4372761	total: 685ms	remaining: 8.83s
72:	learn: 3.4165667	total: 691ms	remaining: 8.78s
73:	learn: 3.4067202	total: 696ms	remaining: 8.71s
74:	learn: 3.3937496	total: 700ms	remaining: 8.64s
75:	learn: 3.3847754	total: 710ms	remaining: 8.63s
76:	learn: 3.3687867	total: 717ms	remaining: 8.59s
77:	learn: 3.3567420	total: 725ms	remaining: 8.57s
78:	learn: 3.3401705	total: 730ms	remaining: 8.51s
79:	learn: 3.3319372	total: 737ms	remaining: 8.48s
80:	learn: 3.3210362	total: 743ms	remaining: 8.43s
81:	learn: 3.3099970	total: 749ms	remaining: 8.39s
82:	learn: 3.3013263	total: 757ms	remaining: 8.36s
83:	learn: 3.2876806	total: 769ms	remaining: 8.38s
84:	learn: 3.2745036	total: 774ms	remaining: 8.34s
85:	learn: 3.2623798	total: 781ms	remaining: 8.3s
86:	learn: 3.2544846	total: 787ms	remaining: 8.26s
87:	learn: 3.2432234	total: 794ms	remaining: 8.23s
88:	learn: 3.2318291	total: 800ms	remaining: 8.19s
89:	learn: 3.2201187	total: 806ms	remaining: 8.15s
90:	learn: 3.2111882	total: 812ms	remaining: 8.11s
91:	learn: 3.2026819	total: 816ms	remaining: 8.05s
92:	learn: 3.1929450	total: 825ms	remaining: 8.04s
93:	learn: 3.1791446	total: 831ms	remaining: 8.01s
94:	learn: 3.1674268	total: 843ms	remaining: 8.03s
95:	learn: 3.1551404	total: 851ms	remaining: 8.01s
96:	learn: 3.1469160	total: 858ms	remaining: 7.99s
97:	learn: 3.1327450	total: 865ms	remaining: 7.96s
98:	learn: 3.1210968	total: 876ms	remaining: 7.97s
99:	learn: 3.1142353	total: 898ms	remaining: 8.08s
100:	learn: 3.1011646	total: 910ms	remaining: 8.1s
101:	learn: 3.0860352	total: 921ms	remaining: 8.11s
102:	learn: 3.0832828	total: 935ms	remaining: 8.15s
103:	learn: 3.0715453	total: 948ms	remaining: 8.17s
104:	learn: 3.0455183	total: 961ms	remaining: 8.19s
105:	learn: 3.0414265	total: 974ms	remaining: 8.21s
106:	learn: 3.0289269	total: 988ms	remaining: 8.24s
107:	learn: 3.0257198	total: 996ms	remaining: 8.23s
108:	learn: 3.0146991	total: 1.01s	remaining: 8.24s
109:	learn: 3.0054561	total: 1.11s	remaining: 9.02s
110:	learn: 2.9930815	total: 1.12s	remaining: 8.99s
111:	learn: 2.9784713	total: 1.13s	remaining: 8.95s
112:	learn: 2.9672580	total: 1.14s	remaining: 8.93s
113:	learn: 2.9573063	total: 1.14s	remaining: 8.88s
114:	learn: 2.9391480	total: 1.15s	remaining: 8.87s
115:	learn: 2.9283831	total: 1.16s	remaining: 8.87s
116:	learn: 2.9157170	total: 1.17s	remaining: 8.86s
117:	learn: 2.9065365	total: 1.19s	remaining: 8.88s
118:	learn: 2.9051253	total: 1.2s	remaining: 8.9s
119:	learn: 2.8971156	total: 1.22s	remaining: 8.91s
120:	learn: 2.8886704	total: 1.28s	remaining: 9.34s
121:	learn: 2.8834545	total: 1.3s	remaining: 9.39s
122:	learn: 2.8750914	total: 1.31s	remaining: 9.36s
123:	learn: 2.8651878	total: 1.32s	remaining: 9.33s
124:	learn: 2.8600165	total: 1.44s	remaining: 10.1s
125:	learn: 2.8514270	total: 1.47s	remaining: 10.2s
126:	learn: 2.8508735	total: 1.48s	remaining: 10.1s
127:	learn: 2.8451718	total: 1.49s	remaining: 10.1s
128:	learn: 2.8392953	total: 1.51s	remaining: 10.2s
129:	learn: 2.8325542	total: 1.53s	remaining: 10.2s
130:	learn: 2.8197823	total: 1.54s	remaining: 10.2s
131:	learn: 2.8069767	total: 1.55s	remaining: 10.2s
132:	learn: 2.7990439	total: 1.56s	remaining: 10.2s
133:	learn: 2.7937501	total: 1.6s	remaining: 10.4s
134:	learn: 2.7851686	total: 1.63s	remaining: 10.4s
135:	learn: 2.7771589	total: 1.8s	remaining: 11.4s
136:	learn: 2.7674574	total: 1.83s	remaining: 11.5s
137:	learn: 2.7624344	total: 1.84s	remaining: 11.5s
138:	learn: 2.7557948	total: 1.85s	remaining: 11.5s
139:	learn: 2.7540610	total: 1.87s	remaining: 11.5s
140:	learn: 2.7416341	total: 1.88s	remaining: 11.5s
141:	learn: 2.7356191	total: 1.9s	remaining: 11.5s
142:	learn: 2.7304987	total: 1.92s	remaining: 11.5s
143:	learn: 2.7212305	total: 1.93s	remaining: 11.5s
144:	learn: 2.7149222	total: 1.93s	remaining: 11.4s
145:	learn: 2.7096813	total: 1.94s	remaining: 11.3s
146:	learn: 2.7061859	total: 1.94s	remaining: 11.3s
147:	learn: 2.6997044	total: 1.95s	remaining: 11.2s
148:	learn: 2.6937199	total: 1.95s	remaining: 11.2s
149:	learn: 2.6869376	total: 1.96s	remaining: 11.1s
150:	learn: 2.6829346	total: 1.96s	remaining: 11s
151:	learn: 2.6781984	total: 1.97s	remaining: 11s
152:	learn: 2.6741214	total: 1.97s	remaining: 10.9s
153:	learn: 2.6689468	total: 1.98s	remaining: 10.9s
154:	learn: 2.6628670	total: 1.98s	remaining: 10.8s
155:	learn: 2.6599378	total: 1.99s	remaining: 10.8s
156:	learn: 2.6588813	total: 1.99s	remaining: 10.7s
157:	learn: 2.6548481	total: 2s	remaining: 10.6s
158:	learn: 2.6505651	total: 2s	remaining: 10.6s
159:	learn: 2.6413885	total: 2.01s	remaining: 10.6s
160:	learn: 2.6353397	total: 2.02s	remaining: 10.5s
161:	learn: 2.6265145	total: 2.02s	remaining: 10.5s
162:	learn: 2.6177499	total: 2.03s	remaining: 10.4s
163:	learn: 2.6079879	total: 2.03s	remaining: 10.4s
164:	learn: 2.6033829	total: 2.04s	remaining: 10.3s
165:	learn: 2.5990173	total: 2.04s	remaining: 10.3s
166:	learn: 2.5882293	total: 2.05s	remaining: 10.2s
167:	learn: 2.5818699	total: 2.06s	remaining: 10.2s
168:	learn: 2.5721028	total: 2.06s	remaining: 10.1s
169:	learn: 2.5700494	total: 2.06s	remaining: 10.1s
170:	learn: 2.5632836	total: 2.07s	remaining: 10s
171:	learn: 2.5629067	total: 2.07s	remaining: 9.98s
172:	learn: 2.5533048	total: 2.08s	remaining: 9.93s
173:	learn: 2.5446215	total: 2.08s	remaining: 9.89s
174:	learn: 2.5350746	total: 2.09s	remaining: 9.84s
175:	learn: 2.5303725	total: 2.09s	remaining: 9.79s
176:	learn: 2.5269267	total: 2.1s	remaining: 9.76s
177:	learn: 2.5252231	total: 2.1s	remaining: 9.71s
178:	learn: 2.5220280	total: 2.11s	remaining: 9.68s
179:	learn: 2.5136653	total: 2.11s	remaining: 9.63s
180:	learn: 2.5093617	total: 2.12s	remaining: 9.59s
181:	learn: 2.5057618	total: 2.13s	remaining: 9.55s
182:	learn: 2.5022650	total: 2.13s	remaining: 9.51s
183:	learn: 2.4922817	total: 2.14s	remaining: 9.47s
184:	learn: 2.4886937	total: 2.14s	remaining: 9.44s
185:	learn: 2.4831221	total: 2.15s	remaining: 9.4s
186:	learn: 2.4812241	total: 2.15s	remaining: 9.36s
187:	learn: 2.4693851	total: 2.16s	remaining: 9.33s
188:	learn: 2.4690828	total: 2.16s	remaining: 9.28s
189:	learn: 2.4616921	total: 2.17s	remaining: 9.24s
190:	learn: 2.4597088	total: 2.18s	remaining: 9.22s
191:	learn: 2.4569668	total: 2.18s	remaining: 9.19s
192:	learn: 2.4518739	total: 2.19s	remaining: 9.16s
193:	learn: 2.4471538	total: 2.2s	remaining: 9.13s
194:	learn: 2.4401576	total: 2.21s	remaining: 9.11s
195:	learn: 2.4387900	total: 2.21s	remaining: 9.08s
196:	learn: 2.4349350	total: 2.22s	remaining: 9.07s
197:	learn: 2.4321425	total: 2.24s	remaining: 9.06s
198:	learn: 2.4250825	total: 2.24s	remaining: 9.03s
199:	learn: 2.4203543	total: 2.25s	remaining: 9.01s
200:	learn: 2.4180240	total: 2.26s	remaining: 8.98s
201:	learn: 2.4112238	total: 2.27s	remaining: 8.95s
202:	learn: 2.4064869	total: 2.27s	remaining: 8.92s
203:	learn: 2.4044499	total: 2.28s	remaining: 8.89s
204:	learn: 2.4010319	total: 2.29s	remaining: 8.86s
205:	learn: 2.3932362	total: 2.29s	remaining: 8.83s
206:	learn: 2.3867932	total: 2.3s	remaining: 8.82s
207:	learn: 2.3819010	total: 2.31s	remaining: 8.79s
208:	learn: 2.3810920	total: 2.32s	remaining: 8.77s
209:	learn: 2.3766365	total: 2.32s	remaining: 8.73s
210:	learn: 2.3708488	total: 2.33s	remaining: 8.7s
211:	learn: 2.3673483	total: 2.33s	remaining: 8.68s
212:	learn: 2.3648943	total: 2.34s	remaining: 8.64s
213:	learn: 2.3621440	total: 2.35s	remaining: 8.62s
214:	learn: 2.3619092	total: 2.35s	remaining: 8.58s
215:	learn: 2.3605382	total: 2.35s	remaining: 8.54s
216:	learn: 2.3583397	total: 2.36s	remaining: 8.52s
217:	learn: 2.3570329	total: 2.37s	remaining: 8.48s
218:	learn: 2.3502476	total: 2.37s	remaining: 8.45s
219:	learn: 2.3462208	total: 2.38s	remaining: 8.43s
220:	learn: 2.3403385	total: 2.38s	remaining: 8.39s
221:	learn: 2.3378410	total: 2.38s	remaining: 8.36s
222:	learn: 2.3332501	total: 2.39s	remaining: 8.33s
223:	learn: 2.3319185	total: 2.4s	remaining: 8.3s
224:	learn: 2.3273848	total: 2.4s	remaining: 8.27s
225:	learn: 2.3207982	total: 2.41s	remaining: 8.24s
226:	learn: 2.3145153	total: 2.41s	remaining: 8.21s
227:	learn: 2.3072196	total: 2.42s	remaining: 8.18s
228:	learn: 2.3043472	total: 2.42s	remaining: 8.16s
229:	learn: 2.3018489	total: 2.43s	remaining: 8.13s
230:	learn: 2.2963128	total: 2.43s	remaining: 8.1s
231:	learn: 2.2936360	total: 2.44s	remaining: 8.08s
232:	learn: 2.2874093	total: 2.44s	remaining: 8.05s
233:	learn: 2.2843254	total: 2.45s	remaining: 8.02s
234:	learn: 2.2776183	total: 2.46s	remaining: 7.99s
235:	learn: 2.2753226	total: 2.46s	remaining: 7.96s
236:	learn: 2.2706111	total: 2.46s	remaining: 7.94s
237:	learn: 2.2651472	total: 2.47s	remaining: 7.92s
238:	learn: 2.2628339	total: 2.48s	remaining: 7.89s
239:	learn: 2.2566844	total: 2.48s	remaining: 7.86s
240:	learn: 2.2551083	total: 2.49s	remaining: 7.84s
241:	learn: 2.2489487	total: 2.49s	remaining: 7.81s
242:	learn: 2.2409464	total: 2.5s	remaining: 7.79s
243:	learn: 2.2382943	total: 2.5s	remaining: 7.76s
244:	learn: 2.2359594	total: 2.51s	remaining: 7.73s
245:	learn: 2.2343108	total: 2.51s	remaining: 7.7s
246:	learn: 2.2282797	total: 2.52s	remaining: 7.67s
247:	learn: 2.2204928	total: 2.52s	remaining: 7.65s
248:	learn: 2.2185693	total: 2.52s	remaining: 7.62s
249:	learn: 2.2162675	total: 2.53s	remaining: 7.59s
250:	learn: 2.2117201	total: 2.54s	remaining: 7.57s
251:	learn: 2.2083604	total: 2.54s	remaining: 7.54s
252:	learn: 2.2051350	total: 2.55s	remaining: 7.52s
253:	learn: 2.2000169	total: 2.55s	remaining: 7.49s
254:	learn: 2.1948700	total: 2.55s	remaining: 7.46s
255:	learn: 2.1887894	total: 2.56s	remaining: 7.43s
256:	learn: 2.1851940	total: 2.56s	remaining: 7.41s
257:	learn: 2.1833940	total: 2.57s	remaining: 7.38s
258:	learn: 2.1819414	total: 2.57s	remaining: 7.35s
259:	learn: 2.1765389	total: 2.58s	remaining: 7.33s
260:	learn: 2.1703493	total: 2.58s	remaining: 7.31s
261:	learn: 2.1658161	total: 2.58s	remaining: 7.28s
262:	learn: 2.1594003	total: 2.59s	remaining: 7.26s
263:	learn: 2.1580539	total: 2.6s	remaining: 7.24s
264:	learn: 2.1550476	total: 2.6s	remaining: 7.21s
265:	learn: 2.1536551	total: 2.61s	remaining: 7.19s
266:	learn: 2.1484171	total: 2.61s	remaining: 7.17s
267:	learn: 2.1431573	total: 2.62s	remaining: 7.14s
268:	learn: 2.1419293	total: 2.62s	remaining: 7.13s
269:	learn: 2.1390427	total: 2.63s	remaining: 7.1s
270:	learn: 2.1356884	total: 2.63s	remaining: 7.08s
271:	learn: 2.1310635	total: 2.64s	remaining: 7.06s
272:	learn: 2.1278915	total: 2.64s	remaining: 7.03s
273:	learn: 2.1242239	total: 2.65s	remaining: 7.01s
274:	learn: 2.1197543	total: 2.65s	remaining: 6.99s
275:	learn: 2.1170372	total: 2.65s	remaining: 6.97s
276:	learn: 2.1142935	total: 2.66s	remaining: 6.94s
277:	learn: 2.1099871	total: 2.66s	remaining: 6.91s
278:	learn: 2.1074851	total: 2.67s	remaining: 6.89s
279:	learn: 2.1039276	total: 2.67s	remaining: 6.87s
280:	learn: 2.0995838	total: 2.67s	remaining: 6.84s
281:	learn: 2.0946050	total: 2.68s	remaining: 6.82s
282:	learn: 2.0905270	total: 2.68s	remaining: 6.8s
283:	learn: 2.0870214	total: 2.69s	remaining: 6.78s
284:	learn: 2.0826903	total: 2.69s	remaining: 6.75s
285:	learn: 2.0780232	total: 2.69s	remaining: 6.73s
286:	learn: 2.0738346	total: 2.7s	remaining: 6.71s
287:	learn: 2.0717527	total: 2.7s	remaining: 6.68s
288:	learn: 2.0662507	total: 2.71s	remaining: 6.66s
289:	learn: 2.0637420	total: 2.71s	remaining: 6.64s
290:	learn: 2.0626251	total: 2.72s	remaining: 6.62s
291:	learn: 2.0615541	total: 2.72s	remaining: 6.6s
292:	learn: 2.0558976	total: 2.73s	remaining: 6.58s
293:	learn: 2.0535938	total: 2.73s	remaining: 6.56s
294:	learn: 2.0506028	total: 2.74s	remaining: 6.54s
295:	learn: 2.0457947	total: 2.74s	remaining: 6.52s
296:	learn: 2.0417714	total: 2.75s	remaining: 6.5s
297:	learn: 2.0378810	total: 2.75s	remaining: 6.48s
298:	learn: 2.0335123	total: 2.75s	remaining: 6.46s
299:	learn: 2.0302559	total: 2.76s	remaining: 6.43s
300:	learn: 2.0292337	total: 2.76s	remaining: 6.42s
301:	learn: 2.0262690	total: 2.77s	remaining: 6.4s
302:	learn: 2.0228492	total: 2.77s	remaining: 6.38s
303:	learn: 2.0206801	total: 2.78s	remaining: 6.36s
304:	learn: 2.0196210	total: 2.78s	remaining: 6.34s
305:	learn: 2.0160454	total: 2.79s	remaining: 6.32s
306:	learn: 2.0126131	total: 2.8s	remaining: 6.32s
307:	learn: 2.0095836	total: 2.8s	remaining: 6.3s
308:	learn: 2.0058517	total: 2.81s	remaining: 6.28s
309:	learn: 2.0039530	total: 2.81s	remaining: 6.26s
310:	learn: 2.0002634	total: 2.82s	remaining: 6.24s
311:	learn: 1.9972364	total: 2.82s	remaining: 6.23s
312:	learn: 1.9936840	total: 2.83s	remaining: 6.21s
313:	learn: 1.9905484	total: 2.83s	remaining: 6.19s
314:	learn: 1.9870637	total: 2.84s	remaining: 6.17s
315:	learn: 1.9838987	total: 2.84s	remaining: 6.15s
316:	learn: 1.9821589	total: 2.85s	remaining: 6.13s
317:	learn: 1.9787405	total: 2.85s	remaining: 6.11s
318:	learn: 1.9752865	total: 2.86s	remaining: 6.1s
319:	learn: 1.9719917	total: 2.86s	remaining: 6.08s
320:	learn: 1.9694380	total: 2.87s	remaining: 6.06s
321:	learn: 1.9668561	total: 2.87s	remaining: 6.05s
322:	learn: 1.9643094	total: 2.88s	remaining: 6.03s
323:	learn: 1.9611325	total: 2.88s	remaining: 6.01s
324:	learn: 1.9535249	total: 2.88s	remaining: 5.99s
325:	learn: 1.9465629	total: 2.89s	remaining: 5.97s
326:	learn: 1.9445156	total: 2.89s	remaining: 5.95s
327:	learn: 1.9415434	total: 2.9s	remaining: 5.93s
328:	learn: 1.9379193	total: 2.9s	remaining: 5.92s
329:	learn: 1.9350311	total: 2.91s	remaining: 5.9s
330:	learn: 1.9321145	total: 2.91s	remaining: 5.88s
331:	learn: 1.9303705	total: 2.92s	remaining: 5.87s
332:	learn: 1.9256533	total: 2.92s	remaining: 5.85s
333:	learn: 1.9228625	total: 2.92s	remaining: 5.83s
334:	learn: 1.9183522	total: 2.93s	remaining: 5.82s
335:	learn: 1.9156660	total: 2.93s	remaining: 5.8s
336:	learn: 1.9134681	total: 2.94s	remaining: 5.78s
337:	learn: 1.9097306	total: 2.94s	remaining: 5.76s
338:	learn: 1.9031764	total: 2.95s	remaining: 5.75s
339:	learn: 1.9007616	total: 2.95s	remaining: 5.73s
340:	learn: 1.8956068	total: 2.95s	remaining: 5.71s
341:	learn: 1.8916920	total: 2.96s	remaining: 5.7s
342:	learn: 1.8885572	total: 2.96s	remaining: 5.68s
343:	learn: 1.8850042	total: 2.97s	remaining: 5.66s
344:	learn: 1.8845855	total: 2.97s	remaining: 5.65s
345:	learn: 1.8814849	total: 2.98s	remaining: 5.63s
346:	learn: 1.8807647	total: 2.98s	remaining: 5.61s
347:	learn: 1.8784583	total: 3.02s	remaining: 5.67s
348:	learn: 1.8753002	total: 3.04s	remaining: 5.66s
349:	learn: 1.8738018	total: 3.05s	remaining: 5.67s
350:	learn: 1.8710421	total: 3.06s	remaining: 5.66s
351:	learn: 1.8694462	total: 3.06s	remaining: 5.64s
352:	learn: 1.8685721	total: 3.08s	remaining: 5.65s
353:	learn: 1.8681873	total: 3.09s	remaining: 5.64s
354:	learn: 1.8663225	total: 3.09s	remaining: 5.62s
355:	learn: 1.8617465	total: 3.1s	remaining: 5.61s
356:	learn: 1.8614029	total: 3.1s	remaining: 5.59s
357:	learn: 1.8588363	total: 3.11s	remaining: 5.58s
358:	learn: 1.8561488	total: 3.11s	remaining: 5.56s
359:	learn: 1.8532461	total: 3.12s	remaining: 5.55s
360:	learn: 1.8480487	total: 3.13s	remaining: 5.53s
361:	learn: 1.8465053	total: 3.13s	remaining: 5.51s
362:	learn: 1.8461985	total: 3.13s	remaining: 5.5s
363:	learn: 1.8444330	total: 3.14s	remaining: 5.49s
364:	learn: 1.8415970	total: 3.14s	remaining: 5.47s
365:	learn: 1.8400459	total: 3.15s	remaining: 5.46s
366:	learn: 1.8374099	total: 3.16s	remaining: 5.45s
367:	learn: 1.8366825	total: 3.16s	remaining: 5.43s
368:	learn: 1.8349428	total: 3.17s	remaining: 5.42s
369:	learn: 1.8319281	total: 3.17s	remaining: 5.41s
370:	learn: 1.8290035	total: 3.18s	remaining: 5.4s
371:	learn: 1.8281099	total: 3.19s	remaining: 5.38s
372:	learn: 1.8278205	total: 3.19s	remaining: 5.37s
373:	learn: 1.8249994	total: 3.2s	remaining: 5.36s
374:	learn: 1.8220625	total: 3.21s	remaining: 5.35s
375:	learn: 1.8190550	total: 3.21s	remaining: 5.34s
376:	learn: 1.8187852	total: 3.22s	remaining: 5.32s
377:	learn: 1.8185372	total: 3.23s	remaining: 5.32s
378:	learn: 1.8168624	total: 3.23s	remaining: 5.3s
379:	learn: 1.8149260	total: 3.24s	remaining: 5.29s
380:	learn: 1.8137998	total: 3.25s	remaining: 5.28s
381:	learn: 1.8123830	total: 3.25s	remaining: 5.26s
382:	learn: 1.8101409	total: 3.26s	remaining: 5.25s
383:	learn: 1.8091251	total: 3.26s	remaining: 5.23s
384:	learn: 1.8085427	total: 3.27s	remaining: 5.22s
385:	learn: 1.8071178	total: 3.27s	remaining: 5.2s
386:	learn: 1.8054747	total: 3.29s	remaining: 5.21s

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('numric',
                                                  Pipeline(steps=[('Scaling',
                                                                   StandardScaler())]),
                                                  Index(['Year', 'Kilometers_Driven', 'Mileage', 'engine_capacity(cc)',
       'Power_bhp', 'Seats'],
      dtype='object')),
                                                 ('one hot enc',
                                                  Pipeline(steps=[('Encoding '
                                                                   'one hot',
                                                                   OneHotEncoder(drop='first',
                                                                                 sparse_output=False))]),
                                                  ['Fuel_Type',
                                                   'Transmission']),
                                                 ('binary enc',
                                                  Pipeline(steps=[('bin_encodeing',
                                                                   BinaryEncoder())]),
                                                  ['Location', 'Brand_name',
                                                   'Model_name']),
                                                 ('ordinal enc',
                                                  Pipeline(steps=[('ordinal_pip',
                                                                   OrdinalEncoder(categories=[['Fourth '
                                                                                               '& '
                                                                                               'Above',
                                                                                               'Third',
                                                                                               'Second',
                                                                                               'First']]))]),
                                                  ['Owner_Type'])])),
                ('model',
                 CatBoostRegressor(loss_function='RMSE', random_state=42))])

In [67]:
import joblib

In [70]:
joblib.dump(catboost_finall_pipeline ,'model.pkl')

['model.pkl']

In [53]:
x.sample(4)

,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,engine_capacity(cc),Power_bhp,Seats,Brand_name,Model_name
2400,Delhi,2012,64709,Petrol,Manual,Second,12.80,2354,177.6,5.0,Honda,Accord
4701,Chennai,2011,29000,Petrol,Manual,Second,18.00,995,62.0,5.0,Chevrolet,Spark
5531,Chennai,2013,38000,Diesel,Automatic,First,16.46,2993,258.0,5.0,BMW,7
3295,Hyderabad,2014,88046,Petrol,Automatic,First,10.10,2354,152.0,5.0,Honda,CR-V

In [54]:
catboost_finall_pipeline.predict(x.sample(15)).round(2)

array([ 2.11, 12.1 ,  4.56,  4.46,  8.29,  5.94,  4.42,  2.02,  2.23,
       15.6 ,  5.21,  4.94,  6.05, 59.63,  5.22])

## Deployment

In [71]:
pd.read_csv('cleaned.csv')

,Unnamed: 0,Location,Year,Kilometers_Driven,Fuel_Type,Transmission,Owner_Type,Mileage,engine_capacity(cc),Power_bhp,Seats,Price,Brand_name,Model_name
0,0,Mumbai,2010,72000,CNG,Manual,First,35.91,998,58.16,5.0,1.75,Maruti,Wagon
1,1,Pune,2015,41000,Diesel,Manual,First,19.67,1582,126.20,5.0,12.50,Hyundai,Creta
2,2,Chennai,2011,46000,Petrol,Manual,First,18.20,1199,88.70,5.0,4.50,Honda,Jazz
3,3,Chennai,2012,87000,Diesel,Manual,First,20.77,1248,88.76,7.0,6.00,Maruti,Ertiga
4,4,Coimbatore,2013,40670,Diesel,Automatic,Second,15.20,1968,140.80,5.0,17.74,Audi,A4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5832,5832,Delhi,2014,27365,Diesel,Manual,First,28.40,1248,74.00,5.0,4.75,Maruti,Swift
5833,5833,Jaipur,2015,100000,Diesel,Manual,First,24.40,1120,71.00,5.0,4.00,Hyundai,Xcent
5834,5834,Jaipur,2012,55000,Diesel,Manual,Second,14.00,2498,112.00,8.0,2.90,Mahindra,Xylo
5835,5835,Kolkata,2013,46000,Petrol,Manual,First,18.90,998,67.10,5.0,2.65,Maruti,Wagon
5836,5836,Hyderabad,2011,47000,Diesel,Manual,First,25.44,936,57.60,5.0,2.50,Chevrolet,Beat

In [55]:
import streamlit as st

In [2]:
%%writefile Home.py

import streamlit as st 
import pandas as pd 
import matplotlib.pyplot as plt

# Page Layout
st.set_page_config(layout= 'wide', page_title= 'BMW Car Prices')

st.markdown("""
<h1 style="color:black; text-align:center;">
BMW Cars Prices Project
</h1>
""", unsafe_allow_html=True)

# Image
img = ('download.jpg')
st.image(img, width=390)


#Data 

st.subheader("📊 Column Descriptions")

st.markdown("""
**model:** The BMW car model (e.g., 1 Series, 3 Series, 5 Series).

**year:** Year the car was manufactured.

**price:** Selling price of the car in GBP.

**transmission:** Type of transmission (Automatic, Manual, Semi-Auto).

**mileage:** Distance the car has been driven (in miles).

**fuelType:** Fuel type (Petrol, Diesel, Hybrid, Electric, Other).

**tax:** Annual road tax in GBP.

**mpg:** Fuel efficiency measured in miles per gallon.

**engineSize:** Engine displacement in litres (e.g., 1.5, 2.0, 3.0).
""")

# show sample of the data 
df = pd.read_csv('cleaned.csv' , index_col = 0)
st.dataframe(df)

Overwriting Home.py

In [2]:
%pwd

'd:\\mohamed\\programming\\Epslion AI\\Learning\\43 Machine learning\\17  ML Deployment (Regression)'

In [3]:
! streamlit run Home.py

^C

In [76]:
%cd ..

d:\mohamed\programming\Epslion AI\Learning\43 Machine learning\17  ML Deployment (Regression)

In [77]:
! streamlit run Home.py

^C

In [56]:
import pipreqs

In [59]:
!pipreqs . --force --encoding=utf-8

WARNING: Import named "matplotlib" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "matplotlib" was resolved to "matplotlib:3.11.1" package (https://pypi.org/project/matplotlib/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
WARNING: Import named "pandas" not found locally. Trying to resolve it at the PyPI server.
WARNING: Import named "pandas" was resolved to "pandas:3.0.3" package (https://pypi.org/project/pandas/).
Please, verify manually the final list of requirements.txt to avoid possible dependency confusions.
INFO: Successfully saved requirements file in .\requirements.txt